### PR TITLE
Migration of Home component fx-Layout to Tailwind

### PR DESCRIPTION
**Pull request by s222356873**
**Description**
Replace the fx-Layout with Tailwind -Home component

**Fixes # (issue)**
No issues

## Type of change

_Please delete options that are not relevant._
- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] This change requires a documentation update

# How Has This Been Tested?
**Before**
scrn1

**After**
The home component has been tested before and after the changes. The interface remains same after monitored.

**## Testing Checklist:**

- [x] Tested in latest Chrome
- [x] Tested in latest Firefox

**scrn1**

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code

### CODE REVIEW

**Comment by s222356873** [comment]
@WillamALOWE will be reviewing this

**Comment by WilliamALowe** [comment]
Reviewed 05/12/2023
- MOST fxLayout properties have been replaced with Tailwindcss.
- Changes does not throw any terminal errors.
- Before and After images are NOT reproducible - see images below
**Before**
home-component-no-changes
**After**
home-component-with-changes

- Some minor fixes required, see notes below:
**fxFlex="10"**
- 2 <span> elements improperly migrated. Elements inherit max-width of 10%, flex-basis has not been given any unit. Try flex-basis: 10%.
**#home**
- fxFlex applies flex-grow, shrink and basis, not display: flex. Try correcting to flex-1.
**Missed fxFlex**
- Line 16 contains an unmigrated fxFlex property. Try correcting to flex-1.
**fxLayout="row wrap"
- flex class applies display: flex with row as the default flex-direction. Elements need to inherit the flex-wrap: wrap style. Try correcting to flex-wrap instead of flex-row.
**Other notes**
- Double-check element sizing after changes to ensure they are exactly the same.
- Consider reformatting code with Prettier for consistency.
- Great job everything else :)

**Comment by maddernd** [comment]
@s222356873 the fixes need applying for this, then needs a re reviewing before I can look at it.,

**Comment by s222356873** [comment]
Completed the required changes , before and after images have been attached.
**Before**
**before**
**After**
finalllllll2

**Comment by s222356873** [comment]
@WillamALOWE will be reviewing this

**Comment by WilliamALowe** [comment]
> @WillamALOWE will be reviewing this

I don't see any new changes :)

**Comment by BrianJCal99** [comment]
I made a new PR for this component migration, #133, and it got approved. I already made a PR to the upstream repository as well. It is ready to be merged and waiting to be approved by one of the maintainers.

**Pull request closed without merging**
