### PR TITLE
refactor(migration): replace-fx-layout-with-tailwind-equivalent-hero-side-bar

### PR DESCRIPTION
**Pull request by syedfaiq**
Replaced fx-layout with equivalent tailwind maintaining the quality of the hero side-bar

### CODE REVIEW

**Comment by syedfaiq** [comment]
Before:
image

After:
image

**Comment by syedfaiq** [comment]
Before:
image

After:
image

**Comment by maddernd** [comment]
Ok this one looks good, please can you resubmit it now to doubtfire-lms/doubtfire-web for the final review

**Comment by maddernd** [comment]
Hi Faiq, just looking at the after screenshot, the username and password boxes still look to be shorter than the previous one. Can you confirm if they are exactly the same?

**Pull request closed without merging**
