### PR TITLE
portfolio.coffee migration initial commit

### PR DESCRIPTION
**Pull request by s222356873**
# Description
This allows user to create their learning summary report at the end of the unit.

Fixes # (issue)
No issues

## Type of change
1.Migrated from angular.js to angular
2.Markdown documentation has been completed

# How Has This Been Tested?
Successfully tested with given credentials. Please refer the changes of following images ( before and after)

**Before :**
portfolio_before

**After**
portfolio_after

## Testing Checklist:

- [x] Tested in latest Chrome
- [x] Tested in latest Safari
- [x] Tested in latest Firefox

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have requested a review from @macite and @jakerenzella on the Pull Request

### CODE REVIEW

**Comment by s222356873** [comment]
Please refer the documentation
[https://github.com/thoth-tech/documentation/pull/507](url)

**Review by Knightwau2 — APPROVED** [review]
hi samadhi, great work!

**Comment by ZHONGYU1111** [comment]
Review:

The replacement files are created successfully.
The old component is unlinked and new component is successfully added.
HTML, CoffeeScript, and SCSS are migrated successfully and no error
The website remain the same as picture shows
Great. It is good to upstream review!

**Comment by aNebula** [comment]
You have not deleted the original 'portfolio.coffee', so this needs to be fixed. @s222356873 you can still get this fixed and merged into 'doubtfire-lms' from your private github for your personal portfolio.

**Pull request closed without merging**
