### PR TITLE
refactor(migration): replace fxlayout with tailwind equivalent in we…

### PR DESCRIPTION
**Pull request by BrianJCal99**
# Description

Replaced FxLayout components with Tailwind equivalent while maintaining the visual appearance and responsiveness of the application. (welcome component)

## Before

image

image

## After

image

image

### CODE REVIEW

**Comment by BrianJCal99** [comment]
@WilliamALowe will review this PR.

**Comment by WilliamALowe** [comment]
Reviewed on 07/12/2023

- All fxLayout properties have been replaced with appropriate Tailwindcss equivalents.
- Changes does not throw any terminal errors.
- Minor issues found, see below:

**hero-sidebar**
- should be visible at width: >= 960px and greater, currently not visible at exact width = 960px.
- currently unsure about hero-sidebar-layout.scss alterations, does seem to work as intended, and no obvious issues, but need to ensure that change won't affect other components that use the hero-sidebar. Consider wrapping element and creating media query in sign-in.component.scss??? Potentially query for Daniel.

**.watermark**
- logo only visible at width < 768px, should be visible at < 960px.

**Comment by BrianJCal99** [comment]
Fixed all above-mentioned minor issues, ready to review @WilliamALowe 

image

image

image

- Had to alter the hero-sidebar-layout.scss file to achieve the correct responsiveness, couldn't do it using Tailwind due to restrictions. (Changing the configuration file for tailwind, which could cause major responsive issues in the entire application)

**Comment by WilliamALowe** [comment]
Re-reviewed on 08/12/2023
- All fxLayout properties have been replaced with appropriate Tailwindcss equivalents.
- Changes does not throw any terminal errors.
- Before and After images are reproducible and appear identical.
- Inspection with browser dev tools shows exact same spacings.
Ready for Upstream review

**Comment by BrianJCal99** [comment]
Hey @maddernd, this PR is ready for upstream review.

**Comment by maddernd** [comment]
This one is good to go for upstream creation to doubtfire-lms

**Pull request closed without merging**
