### PR TITLE
Migrate/timeout

### PR DESCRIPTION
**Pull request by sylvia0929**
Overview
This PR migrates the timeout component from AngularJS and CoffeeScript to Angular 17 and TypeScript.

Changes Made
Component Migration: The timeout component has been updated to use Angular 17 with TypeScript.
File Structure: Created new files for the component in the src/app/errors/states/timeout/ directory:
timeout.component.ts (TypeScript file for the component logic)
timeout.component.html (HTML template for the component view)

Migration Details
TypeScript Conversion: The component logic has been converted from CoffeeScript to TypeScript, enhancing type safety and improving code readability.
Angular Update: The component now utilizes Angular 17 features, aligning with the latest Angular practices and improvements.

Screenshots
Before Migration: 
image (1)

After Migration: 

image (2)

Additional Notes
This migration aims to modernize the codebase and leverage Angular 17's new features for better performance and maintainability.
Please review the changes and provide feedback.

To view the migrated timeout component, you need to comment out `this.authenticationService.signOut(false);` and use the `http://localhost:4200/#/timeout?dest&params` url to load the component, otherwise by default you will be redirected to the sign in page, as the original intended behaviour.

### CODE REVIEW

**Comment by AusBruce** [comment]
Hi sylvia, your timeout component works fine on my local machine, based on your changed the file, you have wrote nice and clean code for front-end migration. your code is clean and readable, nice job you did. It is ready for upstream review!

**Comment by tinahoa** [comment]
Hi Shen, it is working for me now.

**Comment by aNebula** [comment]
Need to remove `timeout.coffee` coffee @sylvia0929 .
@AusBruce and @tinahoa  - this task was incomplete, as the old file did not get removed. This means you have not provided good PR review, and will be penalised during grading.

**Comment by XinHuang1112** [comment]
The migration of the timeout component from AngularJS and CoffeeScript to Angular 17 and TypeScript is well-done.  I can access the timeout component in my local machine. I believe you have completed the migration. 
Great job!

**Comment by sylvia0929** [comment]
this is the previous version of timeout.coffee.  before: image after: 
after

**Comment by b0ink** [comment]
Hi @sylvia0929 

Your migration looks good and is working correctly - the `localhost:4200/#/timeout?dest&params` route logs the current user out and redirects back to the sign in page. I was also able to successfully view the migrated component after commenting out that line of code that logs you out and re-entering the URL again

**Comment by DudeUnleashed** [comment]
As mentioned in the above review, the migration looks good and works as expected. Followed the same steps and got the same results. Component seems successfully migrated.

**Comment by aNebula** [comment]
@sylvia0929 Looks good to me - please open an upstream pull request against [9.x branch of doubtfire-lms/doubtfire-web](https://github.com/doubtfire-lms/doubtfire-web/tree/9.x) to add your changes to upstream and get credited for your contributions in your personal Github portfolio.

**Pull request closed without merging**
