### PR TITLE
#Replaced fx-layout with tailwind equivalent - task-comment-composer

### PR DESCRIPTION
**Pull request by Hashmi125**
Output before : 

Output After : 

## Testing Checklist:

- [x] Tested in latest Chrome
- [ ] Tested in latest Safari
- [ ] Tested in latest Firefox

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have requested a review from @macite and @jakerenzella @Satika @Brian on the Pull Request

### CODE REVIEW

**Comment by satikaj** [comment]
Hi Syed,

I just have some comments regarding your code. I think the format of most lines in the original version of the file was better and easier to read.

In line 23 `<ngx-emoji class="align-items: center"`, you changed `style` to `class` although `style` is the proper keyword as indicated in the original version of the file `<ngx-emoji style="align-items: center"`. Please read up about inline CSS styling which is different from using Tailwind _classes_.

Line 24 `<div class="emoji-details flex flex-col items-center justify-start">` is also incorrect. Please study more about [flex directions and the corresponding main and cross axes](https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_flexible_box_layout/Basic_concepts_of_flexbox). The Tailwind docs specify that the main axis (vertically for `flex-col`) is controlled by [justify content](https://tailwindcss.com/docs/justify-content) while cross axis (horizontally for `flex-col`) is controlled by [align items](https://tailwindcss.com/docs/align-items). Since `fxLayoutAlign="<main-axis> <cross-axis>"`, the code must be `justify-center items-start`.

Changes in line 25 and 26 are also kinda unnecessary considering it uses CSS inline styles instead of fx-layout (e.g. use the original `font-weight: 500` instead of `font-bold`).

On lines 1, 33 and 79 you also removed the occurrences of `this` keyword (e.g. `this.task`, `this.showEmojiPicker`). It doesn't look like a necessary change. Stick to only changing fx-layout keyword occurrences.

Otherwise, the looks of the task-comment-composer looks the same to me including in its various states (userIsTyping, recording, emoji). Please just review your code and make the appropriate changes. Once you're done please test to see if the looks are still the same and send me a message so I could review it again. Thanks.

**Comment by Hashmi125** [comment]
Changes has been made.

**Comment by maddernd** [comment]
@satikaj does this now pass your review?

**Comment by Hashmi125** [comment]
> @satikaj does this now pass your review?

i have opened new PR for this.

**Pull request closed without merging**
