### PR TITLE
refactor: replace fxLayout with tailwind equivalent- calendar-component-migration

### PR DESCRIPTION
**Pull request by AusBruce**
Before:
Picture1

After:
Picture2

# Description

I made the code change from fxLayout to tailwind migration

Fixes # (issue)

## Type of change

_Please delete options that are not relevant._

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] This change requires a documentation update

# How Has This Been Tested?

_Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration_

## Testing Checklist:

- [x] Tested in latest Chrome
- [x] Tested in latest Safari
- [x] Tested in latest Firefox

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have requested a review from @BrianJCal99 on the Pull Request

### CODE REVIEW

**Comment by AusBruce** [comment]
hi this is just a test of fist time pull and request!

**Comment by AusBruce** [comment]
[SIT223_SIT753-3.1GP.pdf](https://github.com/thoth-tech/doubtfire-web/files/13472476/SIT223_SIT753-3.1GP.pdf)

**Review by BrianJCal99 — CHANGES_REQUESTED** [review]
Hey @AusBruce , I can see some fx layout components left in the code. Please fix it so that I can test it on my local machine.

**Comment by AusBruce** [comment]
No worries! I will fix it as soon as possible

**Comment by AusBruce** [comment]
> Hey @AusBruce , I can see some fx layout components left in the code. Please fix it so that I can test it on my local machine.

Hi Brain I had made all changes from fx Layout to Tailwind , can you please help me to review it? Thanks

**Comment by AusBruce** [comment]
hi William can you please help me to review my code? Thank you so much!    @WilliamALowe

**Comment by WilliamALowe** [comment]
Reviewed 11/12/2023
- Most fxLayout properties have been replaced with appropriate Tailwindcss equivalents.
- Changes does not throw any terminal errors.
- Before and After images are NOT reproducible.
- Minor fixes required, see below:

**before and after images are not reproducible**
**before**
calendar-modal-no-changes

**after**
calendar-modal-radio-button

- top right radio button is displaced (see mat-slide-toggle note below)

**div (line 5)**
- flex not necessary as display: flex is not applied to element.
- flex-grow is incorrect for this migration, try applying flex-1 and basis-full classes to maintain flex grow, shrink, and basis styles from fxFlex="grow".

**mat-slide-toggle (line 9)**
- fxFlex missed from migration. 
- try applying flex-1 class to maintain flex grow, shrink, and basis styles from fxFlex.

**div (line 45)**
- fxFlex="grow" missed from migration.
- try applying flex-1 and basis-full classes to maintain flex grow, shrink, and basis styles from fxFlex="grow".

**div (line 75)**
- class property is already present, please move tailwind classes to the already established class property to ensure clean code. 

**code comments**
- please removed commented out old fxLayout elements (lines 4, 43, and 48) to maintain clean code.

**package-lock.json**
- no changes should be made to this file. Ensure that you have not imported new packages.

**Comment by AusBruce** [comment]
Hi Willliam, I really appreciated all the comments you gave here. I did a lot of research to solve those problems.
In the jason file, I made it back to its previous state by resetting the git commit, and lines of code had changed after your instructions.
Also, the before and after webpages had been tested to make sure they were identical.
Thanks for taking the time to review my code and give me some inspiration for front-end development.
You are a very supportive team member.
@WilliamALowe

**Comment by maddernd** [comment]
@WilliamALowe are you happy with this one now.

**Comment by AusBruce** [comment]
Hi Willliam I had synced to the latest version and  made the code change, Can you please review it again to check if i did it correctly? the component is up to date as well @WilliamALowe

**Comment by WilliamALowe** [comment]
Looks good Bruce! Happy to push it to Upstream Review! Great work :)

**Pull request closed without merging**
