### PR TITLE
refactor(migration): replace-fx-layout-with-tailwind-equivalent-sign-in

### PR DESCRIPTION
**Pull request by syedfaiq**
Replaced fx-layout with equivalent tailwind maintaining the quality of the sign-in page

### CODE REVIEW

**Comment by syedfaiq** [comment]
Before:
image

After:
image

**Comment by maddernd** [comment]
Hi Faiq, 

This one the log in box looks a little different, username/password should be on the top line as in the first screenshot.

**Comment by maddernd** [comment]
> Before: image
> 
> After: image

Can you please adjust this so it looks exactly the same as before with the username/password boxes. #64

**Comment by maddernd** [comment]
Hi Faiq, just looking at the after screenshot, the username and password boxes still look to be shorter than the previous one. Can you confirm if they are exactly the same?

**Pull request closed without merging**
