### PR TITLE
refactor: <Replace fx-layout with tailwind equivalent - task-comment- composer>

### PR DESCRIPTION
**Pull request by Hashmi125**
# Description

Replaced:
fxLayout="row" with flex flex-row
fxLayoutAlign="start center" with justify-start items-center
fxLayout="column" with flex flex-col
fxLayoutAlign="center start" with justify-center items-start

## Testing Checklist:

- [x] Tested in latest Chrome
- [x] Tested in latest Safari
- [x] Tested in latest Firefox

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have requested a review from @macite and @jakerenzella on the Pull Request

Before Output : 
p

After Output : 
pp
ppp

### CODE REVIEW

**Comment by maddernd** [comment]
who is reviewing this

**Comment by Hashmi125** [comment]
@satika is reviewing it

**Comment by satikaj** [comment]
Nice work! Thanks a lot for implementing the changes!

One small thing @Hashmi125, on line 57 there are 2 class keywords. You can just combine them into one from `class="flex flex-row items-center justify-around" class="composer-container"` into just `class="flex flex-row items-center justify-around composer-container"`. This error is easy to miss but causes the microphone and other icons to not properly align with the textbox like in the before screenshot. Fixing this would solve it.

**Comment by Hashmi125** [comment]
> Nice work! Thanks a lot for implementing the changes!
> 
> One small thing @Hashmi125, on line 57 there are 2 class keywords. You can just combine them into one from `class="flex flex-row items-center justify-around" class="composer-container"` into just `class="flex flex-row items-center justify-around composer-container"`. This error is easy to miss but causes the microphone and other icons to not properly align with the textbox like in the before screenshot. Fixing this would solve it.

Changed it @satikaj ,  :)

**Comment by BrianJCal99** [comment]
@Hashmi125 This PR is all good. Make a new PR to the upstream repository.

**Comment by satikaj** [comment]
This looks good now, @Hashmi125. Thanks for implementing the changes! 

@maddernd This is now ready for your review.

**Comment by Hashmi125** [comment]
> @maddernd This PR is all good please review it yourself. @Hashmi125  You can make a new PR to the upstream repository now.

Sure, will do !

**Comment by Hashmi125** [comment]
> This looks good now, @Hashmi125. Thanks for implementing the changes! 
> 
> @maddernd This is now ready for your review.

Thanks for reviewing it. @satikaj

**Pull request closed without merging**
