### PR TITLE
Migration: Component of Index.coffee Migration

### PR DESCRIPTION
**Pull request by JayaniVimukthika**
# Description

Migration of the index.coffee component from CoffeeScript and Angular.js to TypeScript and Angular.

This component is used to: Once we login to the ontrack and select the unit/ module, it might takes a few seconds to load the dashboard content/ unit details. This component displays the unit details loading with buffering icon within the time gap of loading unit details is filled by this component.

Fixes # (issue)
No issues

## Type of change

Markdown documentation has been done. Migrated from Angular.js to Angular. 

# How Has This Been Tested?

Successfully tested with given user credentials.
Please refer the images of before and after migration

**Before:**
before index_coffee

**After:**
after index_coffee

## Testing Checklist:

- [x] Tested in latest Chrome
- [ ] Tested in latest Safari
- [ ] Tested in latest Firefox

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings

### CODE REVIEW

**Comment by JayaniVimukthika** [comment]
Please refer the markdown document for the above component.

https://github.com/thoth-tech/documentation/pull/504

**Comment by JayaniVimukthika** [comment]
@ZHONGYU ZHANG will be reviewing this

**Comment by ZHONGYU1111** [comment]
Review:
1. The replacement files are created successfully. 
2. The old component is unlinked and new component is successfully added.
3. HTML, CoffeeScript, and SCSS are migrated successfully and no error
4. The website remain the same as picture shows
Great. It is good to have upstream review!

**Comment by aNebula** [comment]
@JayaniVimukthika Please open a PR to the 'development' branch in the upstream repo https://github.com/doubtfire-lms/doubtfire-web to have it merged for your personal github portfolio.

**Pull request closed without merging**
