### PR TITLE
Migrate/group set manager

### PR DESCRIPTION
**Pull request by s223126445**
Migration of group-set-manager from angular js to angular

# Description

Converting the component from angular js to angular by following the typescript

Fixes # (issue)
Before
before

After
After

## Type of change

_Please delete options that are not relevant._

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

_Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration_

## Testing Checklist:

- [x] Tested in latest Chrome
- [x] Tested in latest Safari
- [x] Tested in latest Firefox

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have requested a review from @macite and @jakerenzella on the Pull Request

### CODE REVIEW

**Comment by DarrenSunandar** [comment]
Reviewed - 14/5/2024

I've check the code thoroughly and it seems like when we login as a convener and go into the group list, the page won't load and it only showing blank page. 
Screenshot 2024-05-14 at 14 17 39

**Comment by s223126445** [comment]
Thank you for the review i will change the description.

**Comment by s223126445** [comment]
Thank you for the review but,its working fine with the admin credentials.

**Comment by maddernd** [comment]
> Reviewed - 12/5/2024
> 
> This pull request including with 5 commits and 8 files changed including 2 deleted files and I think it's good for a migration task.
> 
> * Purpose: Migrate from the old angularjs to angular17 and keep all the features and style the same as before
> * Outcomes: Admin should be able to manage the group such as delete, edit, lock or unlock.
> * Other notes: The system works perfectly same as before and it is ready to be merge



> Reviewed - 12/5/2024
> 
> This pull request including with 5 commits and 8 files changed including 2 deleted files and I think it's good for a migration task.
> 
> * Purpose: Migrate from the old angularjs to angular17 and keep all the features and style the same as before
> * Outcomes: Admin should be able to manage the group such as delete, edit, lock or unlock.
> * Other notes: The system works perfectly same as before and it is ready to be merge

This is not a technical review, its just stating what was in the Commit.

**Comment by maddernd** [comment]
@satikaj can you please review this one if you get a chance.

**Comment by satikaj** [comment]
Are you sure the component you've attached a screenshot of is the group set manager cause when I inspected that it says it's the group set editor. This is the group set manager I found. You can find it when you log in as a convenor and click on a unit then select the Groups view from the dropdown.

image

**Comment by s223126445** [comment]
When i login i can't see anything 
image

**Comment by s223126445** [comment]
@satikaj  Updated the ss Please check 
Thanks
Mounika

**Pull request closed without merging**
