### PR TITLE
refactor: replace fxLayout with tailwind equivalent - intelligent-discussion-player

### PR DESCRIPTION
**Pull request by williamalowe**
# Description

Replaced depreciated fxLayout library implemented with equivalent Tailwindcss for intelligent-discussion-player component component. 

# How Has This Been Tested?

Intelligent discussion components are currently inaccessible due to function not working in current development version. Component was migrated outside of its usual position in the application for testing purposes to ensure styles are maintained. Further testing will be required once service is active again.

before:
intelligent-discussion-player-no-changes

after:
intelligent-discussion-player-tailwind

## Testing Checklist:

- [x] Tested in latest Chrome
- [x] Tested in latest Safari
- [x] Tested in latest Firefox

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] My changes generate no new warnings

### CODE REVIEW

**Comment by WilliamALowe** [comment]
Further review pending - See testing notes

**Comment by WilliamALowe** [comment]
Issue has now been resolved, see updated images below:
**Before**
new-intelligent-discussion-no-changes
**After**
new-intelligent-discussion-player-tailwind

Ready for review

**Comment by WilliamALowe** [comment]
Issue has not been resolved, no changes necessary, see new images below:
**Before**
intelligent-discussion-player-no-changes

**After**
intelligent-discussion-player-tailwind

Ready for review

**Comment by maddernd** [comment]
@WilliamALowe who is reviewing this one?

**Comment by aidandeb** [comment]
- All fxLayout properties have been replaced with appropriate Tailwindcss equivalents.
- Changes does not throw any terminal errors.
- Before and After images are reproducible and appear identical.
- Inspection with browser dev tools shows exact same spacings.

after
before

**Comment by AusBruce** [comment]
I've reviewed the changes where fxLayout was replaced with Tailwind CSS classes.
It's great to see that the refactoring has been done.
I tested the branch locally and didn't encounter any errors.
The 'Before and After' comparisons also confirm that the visual aspects remain unchanged.  @WilliamALowe  Nice work

**Pull request closed without merging**
