### PR TITLE
Migrated components not-found, timeout, unauthorised, alert list

### PR DESCRIPTION
**Pull request by Ishrat420**
# Description

Migrating from Coffeescript to Typescript for web. 

#Components 

Complete Migration done for the following components:
src/app/errors/not-found 
src/app/errors/timeout 
src/app/errors/unauthorised 
src/app/common/alert-list 

##Dependencies and Changes to other files

For migration purposes, had to delete old coffee files: 

        deleted:    src/app/common/alert-list/alert-list.coffee
        deleted:    src/app/errors/states/not-found/not-found.coffee
        deleted:    src/app/errors/states/timeout/timeout.tpl.coffee
        deleted:    src/app/errors/states/unauthorised/unauthorised.coffee

Consequently, made changes to the corresponding states file and module file of the component involved in accordance to the MIGRATION-GUIDE.  

# How Has This Been Tested?

Manually tested each components, works same as before without any performance or technical issue. 

## Testing Checklist:

- [x] Tested in latest Chrome

### Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] My changes generate no new warnings

### CODE REVIEW

**Comment by PerryRose** [comment]
Hi @tancnle, correct me if I'm wrong, but our [branching guidelines](https://github.com/thoth-tech/handbook/blob/main/docs/processes/quality-assurance/git-contribution-guide.md#branching-guidelines) outlines one branch per task/sub-task, correct? Additionally, I believe the component migration tasks need to follow the QA processes and include [unit testing](https://github.com/thoth-tech/handbook/blob/main/docs/processes/quality-assurance/testing-and-dev.md#testing-and-development) before being merged. Let me know if this is correct, Tan. Thanks!

**Comment by Ishrat420** [comment]
> Hi @tancnle, correct me if I'm wrong, but our [branching guidelines](https://github.com/thoth-tech/handbook/blob/main/docs/processes/quality-assurance/git-contribution-guide.md#branching-guidelines) outlines one branch per task/sub-task, correct? Additionally, I believe the component migration tasks are required to follow the QA processes and include [unit testing](https://github.com/thoth-tech/handbook/blob/main/docs/processes/quality-assurance/testing-and-dev.md#testing-and-development) before being merged. Let me know if this is correct, Tan. Thanks!

**Comment by tancnle** [comment]
Thank you for your hard work @Ishrat420 ❤️. I have made some really good progress so far.
Thank you for your feedback on the PR @PerryRose ❤️ .

> Hi @tancnle, correct me if I'm wrong, but our [branching guidelines](https://github.com/thoth-tech/handbook/blob/main/docs/processes/quality-assurance/git-contribution-guide.md#branching-guidelines) outlines one branch per task/sub-task, correct? Additionally, I believe the component migration tasks are required to follow the QA processes and include [unit testing](https://github.com/thoth-tech/handbook/blob/main/docs/processes/quality-assurance/testing-and-dev.md#testing-and-development) before being merged. Let me know if this is correct, Tan. Thanks!

That's a great call-out @PerryRose. I agree. That is the general suggestion. As good practice (good is subjective to teams), we want the smallest change possible, accompanied by tests. It helps to reduce cognitive load for reviewers, speed up code review and reduce surprising bugs. 

@Ishrat420 Please let me know if you need help splitting the changes to multiple PRs and adding tests for them. Or perhaps, if you have capacity @PerryRose, can you help @Ishrat420 ?

**Comment by Ishrat420** [comment]
@tancnle @PerryRose Thank you so much for reviewing my Pr and for your suggestions. Yes it would be great if someone can assist me in regards to splitting the changes in multiple Pr. And if there is a Documentation on how to approach Unit testing, I can definitely work it out.

**Pull request closed without merging**
