### PR TITLE
refactor: remove task-sheet-viewer component

### PR DESCRIPTION
**Pull request by PerryRose**
# Description

This PR removes the task-sheet-viewer component which is not being used anymore in the project. The component usage was removed in commit [679c5dd8e2875c147d0e4167c4fbdfb896b44b4a](https://github.com/thoth-tech/doubtfire-web/commit/679c5dd8e2875c147d0e4167c4fbdfb896b44b4a) (see file: src/app/tasks/task-viewer/task-viewer.tpl.html, line: 78)

## Type of change

- [X] Project clean-up. Removes deprecated code.

# How Has This Been Tested?

Thorough searching to ensure component is not used. 

# Checklist:

- [X] I have performed a self-review of my own code
- [X] I have made corresponding changes to the documentation
- [X] My changes generate no new warnings
- [X] I have requested a review from @tancnle  and @RayGuo-ergou  on the Pull Request

### CODE REVIEW

**Comment by RayGuo-ergou** [comment]
LGTM, but have you confirmed with Andrew will this component be used in future development?

**Comment by PerryRose** [comment]
Let's park this one until Andrew comes back from leave to confirm it's no longer needed.

**Comment by PerryRose** [comment]
[Remove task-sheet-viewer component](https://trello.com/c/cl7uJDEu/39-remove-task-sheet-viewer-component)

**Comment by PerryRose** [comment]
image

@RayGuo-ergou and @tancnle: I got the okay to remove (regarding task-submission-viewer, task-definition-selector, and task-sheet-viewer). I'm assuming this applies for any other unused components we come across.

**Review by RayGuo-ergou — APPROVED** [review]
LGTM

**Review by tancnle — APPROVED** [review]
Thanks for the tidy up, @PerryRose. LGTM 🚀

**Pull request merged**
