### PR TITLE
New/feedback enhancement

### PR DESCRIPTION
**Pull request by coskun-kilinc**
# Description

The commit made several changes:

1. Rebased to properly separate commits for each Trello card, ensuring a clean commit history.
1. Created a new front-end component named `TaskDefinitionStagesComponent` designed to interact with the backend API called `Stages`.

### Task Definition Stages Component

`TaskDefinitionStagesComponent` is an Angular component is used to manage stages in a task definition.

- `@Input() public taskDefinition: TaskDefinition;`: Declares an input property `taskDefinition` of type `TaskDefinition`. The `@Input()` decorator indicates that this property is a public API of the component and its value can be passed in by the component's parent.
- `@ViewChild('stageTable', {static: true}) table: MatTable<any>;`: Declares a view child property named `table`. The `@ViewChild()` decorator is used to access a child component, directive, or a DOM element from a parent component class. In this case, it's used to access the `MatTable` component with the template reference variable `#stageTable`.
- `public columns: string = 'title', 'order', 'criteria', 'cases', 'row-actions';`: Used to define the columns that should be displayed in the table.
- `public get unit(): Unit { return this.taskDefinition?.unit; }`: Getter method for `unit` property. Returns the `unit` property of the `taskDefinition` object.
- `public addStage() {…}`: Used to add a new stage to the `taskDefinition`. Checks if the `stages` property exists in the `taskDefinition` object. If it does, it creates a new stage object and pushes it to the `stages` array. It then calls `this.table.renderRows()` to update the table. Expected to be removed as all taskDefinitions should have a stages property.
- `public removeStage(stage: Stage) {…}`: Remove a stage from the `taskDefinition`. It does this by filtering out the stage from the `stages` array.

## Type of change

- [x] New feature (non-breaking change which adds functionality)
- [x] This change requires a documentation update

# How Has This Been Tested?

Tested by running local instance of OnTrack in both Safari and Chrome. Feature is WIP and not currently functional. 

## Testing Checklist:

- [ ] Tested in latest Chrome
- [x] Tested in latest Safari
- [x] Tested in latest Firefox

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [x] I have requested a review from @ublefo and @satikaj on the Pull Request

### CODE REVIEW

**Comment by maddernd** [comment]
@satikaj please can you review this one.

**Comment by satikaj** [comment]
Hey Josh, if there is a UI change involved, could you please add before and after screenshots? Thanks!

**Comment by satikaj** [comment]
Also my frontend refuses to run currently for 2 reasons:

1. I think you might have to merge the latest changes in development to your branch as a lot of random errors occur in the frontend without those changes from what I have seen testing various things so far.

2. You need to import the TaskDefinitionStagesComponent in the doubtfire-angular.module.ts file otherwise more errors occur.

**Comment by satikaj** [comment]
Hey Josh, I'm able to see the component now. But when I try adding a new stage for an existing task, it shows me this error. It works fine when I do it when adding a new task.

image

**Pull request closed without merging**
