### PR TITLE
Migrate/burn down chart

### PR DESCRIPTION
**Pull request by Saleh3478**
_Any italic text should be deleted from the final Pull Request text, including this line_

# Description

In Progress. 
This pull request for migrating the burn-down-chart component. So far, I did coffee script and html migration. I added a visualization service to get default chart options. I still need to fix two things: combine default and generated options, and call the analytic service.  
 

Fixes # (issue)

## Type of change

- [x] Component Migration

# How Has This Been Tested?

_Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration_

## Testing Checklist:

- [x] Tested in latest Chrome
- [x] Tested in latest Safari
- [x] Tested in latest Firefox

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings

### CODE REVIEW

**Comment by Saleh3478** [comment]
[burn-down-chart migration](https://trello.com/c/yOTNTgdf/43-burn-down-chart-migration)

**Comment by tancnle** [comment]
@Saleh3478 Are you still working on it? If yes, could you please mark this as draft so we know not to start reviewing.

**Comment by Saleh3478** [comment]
> @Saleh3478 Are you still working on it? If yes, could you please mark this as draft so we know not to start reviewing 🙏🏼 .

No. I am not working on it now. I would to get your comments on this version. Thanks

**Comment by tancnle** [comment]
> > @Saleh3478 Are you still working on it? If yes, could you please mark this as draft so we know not to start reviewing 🙏🏼 .
> 
> No. I am not working on it now. I would to get your comments on this version. Thanks

Thanks for confirming @Saleh3478. FWIW, this PR should be assigned to reviewers much earlier. It is a bit late now since we are approaching the end of the trimester 😿 .

**Comment by maddernd** [comment]
no progress

**Pull request closed without merging**
