### PR TITLE
replace fxlayout for inbox comment

### PR DESCRIPTION
**Pull request by qsanah**
# Description

Replace fx-layout with tailwind equivalent - inbox-comment

### CODE REVIEW

**Comment by qsanah** [comment]
Before:
Before

**Comment by qsanah** [comment]
Before:
Before

**Comment by qsanah** [comment]
After:
After

**Review by maddernd — APPROVED** [review]

**Comment by maddernd** [comment]
Ok this looks good, thanks for sending it through. Please can you now create these same Pull request on the upstream repo doubtfire-lms/doubtfire-web, please ensure that you follow contirbuting.md for making sure the PR meets the requirements for a pull request. Once you have made the PR into the upstream we will move the Trello card into Review Upstream.

**Comment by maddernd** [comment]
I think this one looks good, you can make this in  the upstream repo now.

**Comment by qsanah** [comment]
Okay, will do

**Pull request closed without merging**
