### PR TITLE
Description

### PR DESCRIPTION
**Pull request by tinahoa**
Migrate the viewer from CoffeeScript to TypeScript
## Before 

Screenshot 2024-09-19 at 6 35 28 PM
## After
Screenshot 2024-09-19 at 12 09 59 PM

## Type of change

_Please delete options that are not relevant._

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)

# How Has This Been Tested?

Login to tutor account, under task-dropdown menu, select "Task" button to see all the tasks in a specific unit

## Testing Checklist:

- [x] Tested in latest Chrome
- [x] Tested in latest Safari
- [x] Tested in latest Firefox

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings

### CODE REVIEW

**Comment by b0ink** [comment]
Hi @tinahoa 

The new route is working well and loads the task-viewer component with the unit and task definition data correctly

One minor issue i noticed is if you refresh the page after the loading the `/viewer` route, the dropdown menu no longer works and the "selected unit" state is reset

image


You should also delete the `viewer.scss` and `viewer.tpl.html` that was together with `viewer.coffee` as they are no longer being used

Edit: Similar behaviour is also present in the `http://localhost:4200/#/edit_profile` route, where refreshing the page loses the current selected unit - as it also uses the [new TypeScript routing workflow](https://github.com/thoth-tech/doubtfire-web/blob/e70f4c7cd1395eaab942ee389788f75f92e985c9/src/app/doubtfire.states.ts#L191-L203)

**Comment by tinahoa** [comment]
Hi @b0ink, I have removed the old scss and html files. Thank you for reminding me.

**Comment by XinHuang1112** [comment]
The migration of viewer component from AngularJS and CoffeeScript to Angular 17 and TypeScript is well-executed.
Good job, Shen Tian.

**Comment by aNebula** [comment]
> Hi @tinahoa
> 
> The new route is working well and loads the task-viewer component with the unit and task definition data correctly
> 
> One minor issue i noticed is if you refresh the page after the loading the `/viewer` route, the dropdown menu no longer works and the "selected unit" state is reset
> image
> 
> You should also delete the `viewer.scss` and `viewer.tpl.html` that was together with `viewer.coffee` as they are no longer being used
> 
> Edit: Similar behaviour is also present in the `http://localhost:4200/#/edit_profile` route, where refreshing the page loses the current selected unit - as it also uses the [new TypeScript routing workflow](https://github.com/thoth-tech/doubtfire-web/blob/e70f4c7cd1395eaab942ee389788f75f92e985c9/src/app/doubtfire.states.ts#L191-L203)

This issue has not been addressed, hence this PR can not be accepted into the code.

**Pull request closed without merging**
